FROM golang:1.10

# Where factomd sources will live
WORKDIR $GOPATH/src/github.com/Emyrk/twitterbank

# Get the dependencies
COPY ./glide.yaml ./glide.lock ./
COPY vendor ./

# Populate the rest of the source
COPY . .

ARG GOOS=linux

WORKDIR $GOPATH/src/github.com/Emyrk/twitterbank/apiserver/apiserverd
# Build and install factomd
RUN go install

ENTRYPOINT /go/bin/apiserverd -fhost=$FACTOMD_LOC -phost=$PG_HOST