version: "2"

services:
  db:
    container_name: tfa-explorer-database
    build:
      context: .
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      database:
    ports:
      - "5432:5432"

networks:
    database:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.7.0.0/16
                  gateway: 10.7.1.1
                  ip_range: 10.7.1.0/24
